//Sophia Y
//8/20/2025

public class Conversions{
    public static void main(String[] args)
    {
        System.out.println("1. Fahrenheit 2. Celsius");
        System.out.println("1. Celsius 2. Celsius");
        System.out.println("1. Feet 2. Meters");
        System.out.println("1. Meters 2. Feet");
        System.out.println("1. Ounces 2. Millimeters");
        System.out.println("1. Millimeters 2. Ounces");
    }
}
